# 1. Create a 3x3x3 array with random values


In [2]:
import numpy as np
random_array = np.random.rand(3, 3, 3)
print(random_array)


[[[0.64352941 0.98670303 0.81532542]
  [0.5828627  0.33085956 0.97257331]
  [0.77561522 0.14524304 0.60316587]]

 [[0.37240118 0.7417699  0.74769363]
  [0.84644065 0.66954959 0.89760027]
  [0.57505025 0.28291302 0.71976461]]

 [[0.37806626 0.78013532 0.33967083]
  [0.99119246 0.26774953 0.48875449]
  [0.24618953 0.26267773 0.75466366]]]


# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [3]:
import numpy as np
matrix = np.zeros((5, 5))
for i in range(1, 5):
    matrix[i, i - 1] = i
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern


In [4]:
import numpy as np
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix


In [5]:
import numpy as np
random_matrix = np.random.rand(5, 5)
mean_value = random_matrix.mean()
std_deviation = random_matrix.std()
normalized_matrix = (random_matrix - mean_value) / std_deviation
print("Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Random Matrix:
[[0.8306963  0.32501975 0.20823044 0.62801257 0.01646809]
 [0.14058438 0.56795566 0.31110412 0.63584014 0.1410791 ]
 [0.52037405 0.331975   0.2257696  0.56909773 0.24631531]
 [0.87396611 0.29559126 0.59995945 0.32662962 0.83842009]
 [0.1023739  0.00826448 0.94903626 0.6800779  0.49001336]]

Normalized Matrix:
[[ 1.46508922 -0.40491256 -0.83680173  0.7155608  -1.54594266]
 [-1.08695816  0.49346918 -0.45637284  0.74450731 -1.08512869]
 [ 0.31751144 -0.37919191 -0.77194157  0.49769257 -0.69596312]
 [ 1.6251018  -0.51373969  0.61181984 -0.39895925  1.49365195]
 [-1.22826127 -1.57627977  1.90271269  0.9080994   0.20523703]]


# 5. How to find common values between two arrays?

In [6]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print("Common Values:", common_values)

Common Values: [3 4 5]


# 6.How to get the dates of yesterday, today and tomorrow?


In [7]:
from datetime import datetime, timedelta
today = datetime.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)
today_str = today.strftime('%Y-%m-%d')
yesterday_str = yesterday.strftime('%Y-%m-%d')
tomorrow_str = tomorrow.strftime('%Y-%m-%d')
print("Yesterday:", yesterday_str)
print("Today:", today_str)
print("Tomorrow:", tomorrow_str)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [9]:
import numpy as np
A = np.random.rand(7, 7)
B = np.random.rand(7, 7)
if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0

In [10]:
import numpy as np
random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0
print("Random vector with the maximum value replaced:")
print(random_vector)

Random vector with the maximum value replaced:
[0.64786947 0.         0.17131519 0.06825377 0.30865736 0.49700241
 0.28488897 0.26413226 0.64150838 0.91151509]


# 9. How to print all the values of an array?


In [12]:
import numpy as np
arr = np.array([5, 4, 3, 2, 1])
for element in np.nditer(arr):
    print(element)


5
4
3
2
1


# 10.Subtract the mean of each row of a matrix


In [13]:
import numpy as np
matrix = np.random.rand(4, 4)
row_means = np.mean(matrix, axis=1, keepdims=True)
normalized_matrix = matrix - row_means
print("Original Matrix:")
print(matrix)
print("\nMatrix with row means subtracted:")
print(normalized_matrix)


Original Matrix:
[[0.03210748 0.79938351 0.88196113 0.4220054 ]
 [0.1821095  0.27100033 0.75756025 0.82091838]
 [0.34695976 0.19710726 0.25643018 0.83637799]
 [0.61389164 0.72102713 0.80735868 0.29189092]]

Matrix with row means subtracted:
[[-0.5017569   0.26551913  0.34809675 -0.11185898]
 [-0.32578761 -0.23689678  0.24966313  0.31302126]
 [-0.06225904 -0.21211154 -0.15278862  0.42715919]
 [ 0.00534955  0.11248504  0.19881658 -0.31665117]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?


In [14]:
import numpy as np
vector = np.array([1, 2, 3, 4, 5])
indices_to_add_one = np.array([0, 2, 4])
unique_indices = np.unique(indices_to_add_one)
vector[unique_indices] += 1
print(vector)

[2 2 4 4 6]


# 12.How to get the diagonal of a dot product?


In [15]:
import numpy as np
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
matrix_B = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])
dot_product = np.dot(matrix_A, matrix_B)
diagonal = np.diagonal(dot_product)
print("Dot Product:")
print(dot_product)
print("\nDiagonal of the Dot Product:")
print(diagonal)

Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of the Dot Product:
[30 69 90]


# 13.How to find the most frequent value in an array?


In [17]:
import numpy as np
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5])
unique_elements, counts = np.unique(arr, return_counts=True)
most_frequent_index = np.argmax(counts)
most_frequent_value = unique_elements[most_frequent_index]
print("Array:", arr)
print("Most frequent value:", most_frequent_value)
print("Frequency:", counts[most_frequent_index])


Array: [1 2 2 3 3 3 4 4 4 4 5 5 5 5 5]
Most frequent value: 5
Frequency: 5


# 14.How to get the n largest values of an array


In [20]:
import numpy as np
arr = np.array([70, 1, 88, 1, 5, 90, 2, 6, 5, 3])
n = 3
largest_indices = np.argsort(arr)[-n:]
largest_values = arr[largest_indices]
print("Array:", arr)
print(f"{n} largest values:", largest_values)

Array: [70  1 88  1  5 90  2  6  5  3]
3 largest values: [70 88 90]


# 15. How to create a record array from a regular array?


In [21]:
import numpy as np
regular_array = np.array([(1, 'Hitesh', 23),
                          (2, 'Nikhil', 28),
                          (3, 'Jeet', 25)],
                          dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])
record_array = np.rec.fromarrays(regular_array.T, names=regular_array.dtype.names)
print("Record Array:")
print(record_array)

Record Array:
((1, 'Hitesh', 23), (2, 'Nikhil', 28), (3, 'Jeet', 25))


# 16. How to swap two rows of an array?


In [23]:
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
row1_index = 1 
row2_index = 2 
array[row1_index], array[row2_index] = array[row2_index], array[row1_index]
print("Array with rows swapped:")
print(array)

Array with rows swapped:
[[1 2 3]
 [7 8 9]
 [7 8 9]]


# 17. Write python code to reshape to the next dimension of numpy array?



In [24]:
import numpy as np
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = np.reshape(original_array, (2, -1))
print("Original Array:")
print(original_array)
print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]
